### PR TITLE
Fixing my mistake on CartoDB layers

### PR DESCRIPTION
**Pull request by tiagofassoni**
Sorry, aparently I mistook one parameter. I fixed it, and it is running on http://104.236.47.111:8000/

### CODE REVIEW

**Comment by ligfietser** [comment]
Sorry, I can't merge it: This branch has conflicts that must be resolved
I'm not familiar with git so could you please fix this first?

**Comment by ligfietser** [comment]
Thanks Tiago, 
I couldnt merge your branch but I committed it here: 
https://github.com/ligfietser/Bicycle_Tags_Map/commit/65cc7d9d175771b0506a308f0061d72912de1cfa 

----- Oorspronkelijk bericht -----

**Comment by tiagofassoni** [comment]
Hello!

I'm writing on this closed pull request because it was the easiest way to contact you about an issue.
The brazilian cycling community warned me today about ways with ['cycleway:right'=lane] not showing on the Bicycle Tags Map. I spent some time digging and discovered it was because in a commit, 12 days ago, when adding more tags, the ['cycleway:right'=lane] was removed. 

Now, I could, of course, just put it back and make a pull request. But I think the best to do in this situation would be for me to refactor the code so it would be harder to make such mistakes. What do you think?

**Comment by ligfietser** [comment]
Hi Tiago,
Please mail me the improved code, you can contact me ligfietser at online dot nl

**Pull request closed without merging**
